# Generated by Django 6.0.6 on 2026-06-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='evidence',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
