# Generated by Django 6.0.6 on 2026-07-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evidence_file_name_evidence_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='encrypted_file',
            field=models.FileField(blank=True, null=True, upload_to='encrypted_evidence/'),
        ),
    ]
