# Generated by Django 6.0.6 on 2026-07-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trustedcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='backup_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
