# Generated by Django 6.0.6 on 2026-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_type', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='direct_captures/')),
                ('encrypted_file', models.FileField(blank=True, null=True, upload_to='encrypted_direct_captures/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('hash_value', models.CharField(blank=True, max_length=256)),
                ('backup_path', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
