# Generated by Django 6.0.6 on 2026-09-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_directcapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcapture',
            name='evidence_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
