# Generated by Django 6.0.6 on 2026-09-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_directcapture_evidence_id_evidence_evidence_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_id', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
