# Generated by Django 6.0.6 on 2026-09-18 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20260913_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='direct_capture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.directcapture'),
        ),
        migrations.AlterField(
            model_name='report',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.evidence'),
        ),
    ]
