# Generated by Django 6.0.6 on 2026-09-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_report_direct_capture_alter_report_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedcontact',
            name='access_token',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
    ]
